name: daily vulnerability scan

on:
  push:
    branches:
      # - main
      - add_daily-vul-scan
  # pull_request:
  # workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"
          cache: true

      - name: Go modules sync
        run: go mod tidy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        run: |
          make docker-build IMG=zozo-gatling-operator:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: "zozo-gatling-operator:${{ github.sha }}"
          format: "template"
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: "1"
          ignore-unfixed: false
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          timeout: "5m0s"
          scanners: "vuln,secret,config"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
