name: daily vulnerability scan

on:
  push:
    branches:
      # - main
      - add_daily-vul-scan
  # pull_request:
  # workflow_dispatch:

env:
  IMAGE_NAME: zozo-gatling-operator
  TRIVY_RESULT_FILE: trivy-results.md

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Go modules sync
        run: go mod tidy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        run: |
          make docker-build IMG=$IMAGE_NAME:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: $IMAGE_NAME:${{ github.sha }}
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
          timeout: 10m0s
          scanners: vuln,secret,config
          format: template
          template: "@gitrivy.tpl"
          output: $TRIVY_RESULT_FILE

      - name: Insert text into Markdown file
        if: always()
        run: |
          sed -i '1i\
          ---\
          title: [DO NOT CHANGE] Security Alert\
          labels: trivy, vulnerability\
          ---\
          ' $TRIVY_RESULT_FILE

      - uses: JasonEtco/create-an-issue@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: $TRIVY_RESULT_FILE
          update_existing: true
          search_existing: open
