name: daily vulnerability scan

on:
  push:
    branches:
      # - main
      - add_daily-vul-scan
  # pull_request:
  # workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version-file: "./go.mod"
      #     cache: true

      # - name: Go modules sync
      #   run: go mod tidy

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build an image from Dockerfile
      #   run: |
      #     make docker-build IMG=zozo-gatling-operator:${{ github.sha }}

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: image
      #     image-ref: "zozo-gatling-operator:${{ github.sha }}"
      #     format: template
      #     template: "@gitrivy.tpl"
      #     output: trivy-results.md
      #     exit-code: 1
      #     ignore-unfixed: false
      #     vuln-type: "os,library"
      #     severity: "HIGH,CRITICAL"
      #     timeout: "5m0s"
      #     scanners: "vuln,secret,config"

      - name: Insert text into Markdown file
        if: always()
        run: |
          touch ./trivy-results.md
          sed -i '1i\
          ---\
          title: Security Alert\
          ---\
          hogehoge\
          ' ./trivy-results.md

      - uses: JasonEtco/create-an-issue@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./trivy-results.md
          update_existing: false
          search_existing: open
